"""Cross-repo smoke test — verify dynamic evidence patterns generalize.

Runs the same agent against langchain-ai/langgraph (Python framework)
to confirm criteria_parser_node generates appropriate patterns instead
of relying on the old axum-hardcoded ones.
"""
from __future__ import annotations

import functools
import json
import sys
import time
from pathlib import Path

print = functools.partial(print, flush=True)
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

from langgraph.types import Command
import agent

REPO_OWNER = "langchain-ai"
REPO_NAME = "langgraph"
TOP_N = 3
CRITERIA = "Senior Python framework architect. Must-have skills: async, type hints, agent state management."


def main() -> int:
    graph = agent.build_graph()
    config = {"configurable": {"thread_id": f"cross-repo-{int(time.time())}"}}

    init_state = {
        "query": f"Find {TOP_N} contributors in {REPO_OWNER}/{REPO_NAME}",
        "repo_owner": REPO_OWNER,
        "repo_name": REPO_NAME,
        "top_n": TOP_N,
        "criteria_text": CRITERIA,
        "trace": [],
    }

    print("=" * 70)
    print(f"Repo:     {REPO_OWNER}/{REPO_NAME}")
    print(f"Criteria: {CRITERIA}")
    print("=" * 70)

    t0 = time.time()
    for chunk in graph.stream(init_state, config=config, stream_mode="updates"):
        if isinstance(chunk, dict):
            for node_name, delta in chunk.items():
                if not isinstance(delta, dict):
                    continue
                for entry in delta.get("trace", []) or []:
                    print(f"[{entry['node']}] {entry['action']}")

    snap = graph.get_state(config)
    if getattr(snap, "interrupts", ()):
        print("\nINTERRUPT — criteria insufficient (should not happen with this query)")
        return 1

    final = graph.get_state(config).values
    elapsed = time.time() - t0

    parsed = final.get("parsed_criteria", {})
    print()
    print("=" * 70)
    print("DYNAMIC EVIDENCE RULES generated by criteria_parser_node:")
    for rule in parsed.get("evidence_required", []):
        if isinstance(rule, dict):
            print(f"  • {rule.get('name')}")
            print(f"    description: {rule.get('description')}")
            print(f"    patterns: {rule.get('file_path_patterns')}")
            print(f"    min_count: {rule.get('min_count')}")
        else:
            print(f"  • (legacy string) {rule}")
    print("=" * 70)

    payload = final.get("final_report")
    if not payload:
        print("ERROR: no final_report")
        return 1

    candidates = json.loads(payload)
    print(f"\nFINAL TALENT REPORT — {len(candidates)} candidates ({elapsed:.1f}s)")
    print("=" * 70)
    for c in candidates:
        print(f"\n#{c['rank']} {c['username']}  score={c['score']}  "
              f"predicates={c['predicates_passed']}  merged_prs={c['merged_prs']}")
        for p in c.get("passed", []):
            evidence = p.get("evidence", [])
            ev_str = f" ← {evidence[0]}" if evidence and isinstance(evidence[0], str) and evidence[0].startswith("http") else ""
            print(f"  PASS {p['predicate']}{ev_str}")
        for f in c.get("failed", []):
            print(f"  FAIL {f['predicate']} — {f.get('reason','')[:80]}")

    print("\n" + "=" * 70)
    print(f"CROSS-REPO TEST PASSED — agent worked on {REPO_OWNER}/{REPO_NAME}")
    print("Patterns were generated by the parser, NOT hardcoded for axum.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
